services:
  db:
    image: postgres
    container_name: postgre_db
    restart: always
    environment:
      - POSTGRES_USER=senla
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=senladb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U senla -d senladb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data:
